//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//




public class CampoDeFuerza extends HitBox {
	private Int Vida;
	private Boolean existe;
	public Proyectil Unnamed1;
	public Juego Unnamed2;
	public HitBox Unnamed3;
	public HitBox Unnamed6;
	public Void reAparecer() {
	
	}
	
	public Void serDanado(Intl dano) {
	
	}
}
