//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//




public class Enemigo extends Nave {
	private Int velocidadNave;
	public Jugador Unnamed1;
	public Void darPuntos(Jugador jugador) {
	
	}
}
