//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//




public class HitBox {
	private Int ancho;
	private Int alto;
	private Int posicionX;
	public Int posicionY;
	public CampoDeFuerza Unnamed1;
	public Nave Unnamed2;
	public Proyectil Unnamed3;
	public CampoDeFuerza Unnamed4;
}
