//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//




public class Juego {
	private Int Nivel;
	private String Difficultad;
	private Jugador jugador;
	private Int anchoPantalla;
	public Int largoPamtalla;
	private List<Enemigo> enemigos;
	private List<CampoDeFuerza> campoDeFuerza;
	public Nave Unnamed1;
	public CampoDeFuerza Unnamed2;
	public Juego Unnamed3;
	public Juego Unnamed4;
	public Proyectil Unnamed5;
	public Nave Unnamed6;
	public CampoDeFuerza Unnamed7;
	public Proyectil Unnamed8;
	public Void NuevoJuego() {
	
	}
	
	public Void TerminarJuego() {
	
	}
	
	public Void siguienteNivel(Int velocidad, List<CampoDeFuerza> campos, Int puntos) {
	
	}
	
	public Boolean estaEnLaPantalla(Int x, Int y) {
	
	}
	
	public Boolean esEnemigo(HitBox objeto) {
	
	}
	
	public Boolean esCampoDeFuerza(HitBox objeto) {
	
	}
	
	public Boolean esJugador(HitBox objeto) {
	
	}
}
