//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//




public class Jugador extends Nave {
	private String nombre;
	private Int puntaje;
	private Int vida;
	public Jugador Unnamed1;
	public Jugador Unnamed2;
	public Enemigo Unnamed3;
	public Void Reaparecer() {
	
	}
	
	public Int vidasRestantes() {
	
	}
}
