//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//




public abstract class Nave extends HitBox {
	private Int identificador;
	public Proyectil Unnamed1;
	public Juego Unnamed2;
	public HitBox Unnamed5;
	public Proyectil disparar() {
	
	}
	
	public Void moverse() {
	
	}
	
	public void morir() {
	
	}
	
	public void spawn(Int posicion) {
	
	}
	
	public Boolean estaVivo() {
	
	}
}
