//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//




public class Proyectil extends HitBox {
	private Int velocidadProyectil();
	private Int direccionProyectil();
	public Nave Unnamed1;
	public Juego Unnamed3;
	public CampoDeFuerza Unnamed4;
	public Nave Unnamed5;
	public HitBox Unnamed6;
	public Void trayectproa() {
	
	}
	
	public Void destruir() {
	
	}
	
	public Boolean hayEmciemtro(HitBox objetivo) {
	
	}
}
