package elementos;

import valueobject.ProyectilVO;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//




public class Proyectil extends HitBox {
	private int velocidadProyectil;
	private int direccionProyectilY; //Positivo si la dispara un enemigo, negativo si la dispara el jugador
	
	
	public Proyectil(int x,int y, int direccion) {
		super(5, 16, x+8, (direccion>0? y+10 : y-35 )); //crea la hitbox del proyectil, Un poco más arriba si es del jugador, un poco más abajo si es de las naves enemigas
		this.velocidadProyectil = 3;
		this.direccionProyectilY = direccion;
	}
	
	public int getVelocidad() {
		return this.velocidadProyectil;
	}
	public int getDireccion() {
		return this.direccionProyectilY;
	}
	public void destruir() {
	
	}
	
	public boolean hayEncuentro(HitBox objetivo) {
		if(objetivo.getPosicionX() == super.getPosicionX() && objetivo.getPosicionY() == super.getPosicionY()) {
			return true;
		} else {
			return false;
		}
	}
	
	
	public ProyectilVO getPVO() {
		return (new ProyectilVO(this.getPosicionX(),this.getPosicionY(),this.getVelocidad(),this.getDireccion()));
	}
}
