package elementos;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//




public class Proyectil extends HitBox {
	private int velocidadProyectil;
	private int direccionProyectilY;
	
	public Proyectil(int x,int y) {
		super(1, 2, x, y);
		this.velocidadProyectil = 5;
		this.direccionProyectilY = y;
	}
	
	public void destruir() {
	
	}
	
	public boolean hayEncuentro(HitBox objetivo) {
		if(objetivo.getPosicionX() == super.getPosicionX() && objetivo.getPosicionY() == super.getPosicionY()) {
			return true;
		} else {
			return false;
		}
	}
	
	public void moverProyectil() {
		this.direccionProyectilY += this.velocidadProyectil;
		super.setPosicionY(this.direccionProyectilY);
	}
}
