package elementos;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//




public class Proyectil extends HitBox {
	private int velocidadProyectil;
	private int direccionProyectilX;
	private int direccionProyectilY;
	
	public Proyectil(int x, int y) {
		super(1, 2, x, y);
		velocidadProyectil = 5;
		direccionProyectilX = x;
		direccionProyectilY = y;
	}
	
	public void trayectoria(boolean arriba) {
		if(arriba) {
			direccionProyectilY++;
		} else {
			direccionProyectilY--;
		}
	}
	
	/*
	public Void destruir() {
	
	}*/
	
	public boolean hayEncuentro(HitBox objetivo) {
		return false;
	}
}
