package naves;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//

public class Enemigo extends Nave {


	public Enemigo(int x, int y) {
		super(32, 32, x, y);	
		this.vivo = true;
	}

	public void darPuntos(Jugador jugador) {
		jugador.recibirPuntos(10);
	}
	
	public void moverseEjeY(int y) {
		super.setPosicionY(y);
	}
}
