package naves;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//

public class Enemigo extends Nave {
	@SuppressWarnings("unused")
	private int velocidadNave;

	public Enemigo(int x, int y) {
		super(32, 32, x, y);
		this.velocidadNave = 10;		
		this.vivo = true;
	}

	public void darPuntos(Jugador jugador) {
		jugador.recibirPuntos(15);
	}
	
	public void moverseEjeY(int y) {
		super.setPosicionY(y);
	}
	
	public void aumentarVelocidad(int vel) {
		this.velocidadNave += vel;
	}
}
