package naves;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//

public class Enemigo extends Nave {
	private int velocidadNave;

	public Enemigo(int x, int y) {
		super(4,4, x, y);
		this.velocidadNave = 10;		
		this.vivo = true;
	}
	
	// /////////////////////////////

	/*public Void darPuntos(Jugador jugador) {
		ESTE ME PARECE QUE NO VA ACA
	}*/
	
	public void aumentarVelocidad(int vel) {
		this.velocidadNave += vel;
	}
}
