package naves;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//

import app.Juego;
import valueobject.JugadorVO;

public class Jugador extends Nave {
	private int puntaje;
	private int vida;
	
	public Jugador(int x, int y) {
		super(32, 32, x, y);
		this.vivo = true;
		this.vida = 3;
		this.puntaje = 0;
	}
	
	//Trabajar sobre esto
	public void Reaparecer() {
		if(this.vida > 1) {
			this.vida--;
			this.vivo = true;
		}
	}
	
	@Override
	public void moverseEjeX(int x) {
		//ESTO NO ESTA BIEN
		if(Juego.getInstancia().estaEnLaPantalla(super.getPosicionX() + x, super.getPosicionY()))
			if(super.getPosicionX() + x + 32<= Juego.getInstancia().getAnchoPantalla())
				super.setPosicionX(super.getPosicionX() + x);
	}
	
	public int vidasRestantes() {
		return this.vida;
	}
	
	public void restarVida() {
		this.vida = this.vida - 1;
	}
	
	public void recibirPuntos(int puntos) {
		this.puntaje += puntos;
	}

	public int getPuntaje() {
		return puntaje;
	}

	public void setPuntaje(int puntaje) {
		this.puntaje = puntaje;
	}
	public JugadorVO getJugadorVO(){
		return(new JugadorVO(this.getPosicionX(),this.getPosicionY(), this.puntaje,this.vida));
		}

	public void darVida() {
		this.vida+=1;
		
	}

}
