package naves;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//




public class Jugador extends Nave {
	private int puntaje;
	private int vida;
	
	public Jugador(int x, int y) {
		super(4, 4, x, y);
		this.vivo = true;
		this.vida = 3;
		this.puntaje = 0;
	}
	
	//Trabajar sobre esto
	public void Reaparecer() {
		if(this.vida > 1) {
			this.vida--;
			this.vivo = true;
		}
	}
	
	public int vidasRestantes() {
		return this.vida;
	}
	
	public void restarVida() {
		this.vida = this.vida - 1;
	}
	
	public void recibirPuntos(int puntos) {
		this.puntaje += puntos;
	}

	public int getPuntaje() {
		return puntaje;
	}

	public void setPuntaje(int puntaje) {
		this.puntaje = puntaje;
	}
}
