import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//

public class Juego {
	private int nivel;
	private String Difficultad;
	private Jugador jugador;
	private int anchoPantalla;
	private int largoPamtalla;
	private int enemigoSpawnX;
	private int enemigoSpawnY;
	private List<Enemigo> enemigos;
	private List<CampoDeFuerza> camposDeFuerza;
	
	public Juego() {
		this.anchoPantalla = 720;
		this.largoPamtalla = 1024;
		this.enemigoSpawnX = 4;
		this.enemigoSpawnY = 26;
	}
	
	public void NuevoJuego() {
		int auxX = enemigoSpawnX;
		int auxY = enemigoSpawnY;

		this.jugador = new Jugador("PLAYER 1", 4, 4, 0, 0);
		
		for(int i = 0; i < 15; i++) {
			if(i == 0) {
				auxX = enemigoSpawnX;
				auxY = enemigoSpawnY;
			} else if(i == 5) {
				auxX = enemigoSpawnX;
				auxY = enemigoSpawnY - 5;
			} else if(i == 10) {
				auxX = enemigoSpawnX;
				auxY = enemigoSpawnY - 10;
			}
			Enemigo enemigo = new Enemigo(4, 4, auxX, auxY);
			enemigos.add(enemigo);
			
			auxX += 5;
			auxY += 5;
		}
		jugador.spawn();
	}
	
	public void TerminarJuego() {
		enemigos.clear();
		camposDeFuerza.clear();
		
		System.out.println("Termino el Juego");
		System.out.println("Tu puntaje fue de: " + this.jugador.getPuntaje());
	}
	
	public Void siguienteNivel(Int velocidad, List<CampoDeFuerza> campos, Int puntos) {
		this.nivel++;
		int aux = this.jugador.getPuntaje();
		this.jugador.setPuntaje(aux + 500);
	}
	
	public Boolean estaEnLaPantalla(int x, int y) {
		if(x <= anchoPantalla && x >= 0) {
			if(y <= largoPamtalla && y >= 0) return true;
			else return false;
		} else return false;
	}
	/*
	public Boolean esEnemigo(HitBox objeto) {
		while
	}
	
	public Boolean esCampoDeFuerza(HitBox objeto) {
		
	}
	
	public Boolean esJugador(HitBox objeto) {
		jugador
	}
	*/
}
