//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Trabajo Practico Obligatorio
//  @ File Name : space Invaders v1.0
//  @ Date : 2/10/2018
//  @ Author : Parodi Federico, Salvioli Santiago, Yanzon Carlos Santiago
//
//




public class Jugador extends Nave {
	private String nombre;
	private int puntaje;
	private int vida;
	public Jugador Unnamed1;
	public Jugador Unnamed2;
	public Enemigo Unnamed3;
	
	public Jugador(String nom, int an, int al, int x, int y) {
		super(an, al, x, y);
		this.nombre = nom;
		this.vivo = true;
		this.vida = 3;
		this.puntaje = 0;
	}
	
	public void Reaparecer() {
		if(vida > 1) {
			this.vida--;
			this.vivo = true;
		}
	}
	
	public int vidasRestantes() {
		return vida;
	}

	public int getPuntaje() {
		return puntaje;
	}

	public void setPuntaje(int puntaje) {
		this.puntaje = puntaje;
	}
	
	
}
